baseURL = 'https://norishide.github.io/portfolio/'
languageCode = 'ja'
title = 'Noly Higashide'
theme = 'PaperMod'
publishDir = 'docs'

[params]
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowWordCount = true
  ShowRssButtonInSectionTermList = true
  UseHugoToc = true

#[params.homeInfoParams]
#  Title = "Welcome to my portfolio"
#  Content = "This is a sample site using PaperMod theme"

[params.profileMode]
  enabled = true
#  title = "Noriyuki (Noly) Higashide"
  subtitle = "Scientist"
  imageUrl = "/portfolio/images/profile.jpg"
  imageWidth = 360
  imageHeight = 360
  imageTitle = "Profile Picture"

[[params.profileMode.buttons]]
  name = "Posts"
  url = "/portfolio/posts/"

[[params.profileMode.buttons]]
  name = "GitHub"
  url = "https://github.com/norishide"

[[menu.main]]
  identifier = "home"
  name = "Home"
  url = "/"
  weight = 10

[[menu.main]]
  identifier = "posts"
  name = "Posts"
  url = "/posts/"
  weight = 20
